djangoProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from users import views as userViews

urlpatterns = [
    path('museum/', include('museum.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/register/', userViews.register, name='register'),
    path('', RedirectView.as_view(url='museum/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

museum/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # views for everyone
    path('', views.ToursIndexListView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('tour/<int:pk>', views.TourIndexDetailView.as_view(), name='tour-info'),

    # views & actions for visitors and staff
    path('tickets/', views.TicketListView.as_view(), name='tickets'),
    path('tickets/view/<int:pk>', views.TicketDetailView.as_view(), name='ticket-manage'),
    path('tickets/update/<int:pk>', views.TicketUpdateView.as_view(), name='ticket-update'),
    path('tickets/delete/<int:pk>', views.TicketDeleteView.as_view(), name='ticket-delete'),
    path('tickets/new', views.TicketNewView.as_view(), name='ticket-new'),

    path('tours/', views.ToursListView.as_view(), name='tours'),
    path('tours/<int:pk>', views.TourDetailView.as_view(), name='tour-manage'),
    path('tours/update/<int:pk>', views.TourUpdateView.as_view(), name='tour-update'),
    path('tours/delete/<int:pk>', views.TourDeleteView.as_view(), name='tour-delete'),
    path('tours/new', views.TourNewView.as_view(), name='tour-new'),

    path('exhibitions/', views.ExhibitionListView.as_view(), name='exhibitions'),
    path('exhibitions/view/<int:pk>', views.ExhibitionDetailView.as_view(), name='exhibition-manage'),
    path('exhibitions/update/<int:pk>', views.ExhibitionUpdateView.as_view(), name='exhibition-update'),
    path('exhibitions/delete/<int:pk>', views.ExhibitionDeleteView.as_view(), name='exhibition-delete'),
    path('exhibitions/new', views.ExhibitionNewView.as_view(), name='exhibition-new'),

    path('storage', views.StorageListView.as_view(), name='storage'),
    path('storage/view/<int:pk>', views.StorageDetailView.as_view(), name='storage-manage'),
    path('storage/update/<int:pk>', views.StorageUpdateView.as_view(), name='storage-update'),
    path('storage/delete/<int:pk>', views.StorageDeleteView.as_view(), name='storage-delete'),
    path('storage/new', views.StorageNewView.as_view(), name='storage-new'),

    # buying tickets
    path('tickets/buy', views.BuyTicketView.as_view(), name='buy-ticket'),
]

museum/models.py
from django.db import models
from django.urls import reverse
import users
from django.utils.translation import gettext_lazy as _

# Create your models here.


class Tour(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=256, verbose_name=_('Тур'))
    exhibitions = models.ManyToManyField('Exhibition', verbose_name=_('Виставки'))
    date = models.DateTimeField(verbose_name=_('Час виставки'))
    admission = models.BooleanField(verbose_name=_('За записом?'))
    price = models.FloatField(default=0, verbose_name=_('Ціна'))

    def get_absolute_url(self):
        return reverse('tour-manage', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['date']


class Ticket(models.Model):
    id = models.AutoField(primary_key=True)
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE, verbose_name=_('Тур'))
    visitor = models.ForeignKey(users.models.MuseumUser, on_delete=models.CASCADE, verbose_name=_('Відвідувач'))

    def get_absolute_url(self):
        return reverse('ticket-manage', args=[str(self.id)])

    def __str__(self):
        return self.tour + " - " + self.visitor


class Exhibition(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=128, verbose_name=_('Виставка'))
    items = models.ManyToManyField('Item', verbose_name=_('Предмети'))
    tours = models.ManyToManyField(Tour, null=True, blank=True, default=None, verbose_name=_('Тури'))

    def get_absolute_url(self):
        return reverse('exhibition-manage', args=[str(self.id)])

    def __str__(self):
        return self.name


class Item(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=64, verbose_name=_('Предмет'))
    quantity = models.IntegerField(verbose_name=_('Кількість'))
    in_exhibition = models.ForeignKey(Exhibition, null=True, on_delete=models.SET_NULL, default=None, blank=True, verbose_name=_('Виставки'))

    def get_absolute_url(self):
        return reverse('storage-manage', args=[str(self.id)])

    def __str__(self):
        return self.name

djangoProject/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h2> Історія музею </h2>
    <p>МИКОЛАЇВСЬКИЙ ОБЛАСНИЙ КРАЄЗНАВЧИЙ МУЗЕЙ</p>
    <p>15 (28) грудня 1913 року в культурному житті Миколаєва відбулась важлива подія – було відкрито міський
        природничо-історичний музей. Основою його зібрання стала унікальна природнича колекція Е.П. Францова,
        подарована місту його спадкоємцями. В ній були представлені зразки мінералів, опудала птахів, риб, тварин,
        корали, губки, гербарії тропічних рослин та багато інших цікавих речей.</p>
    <p>Процесом створення міського музею опікувалася комісія, до складу якої увійшли депутати місцевої думи на чолі
        з юристом, археологом-аматором С.І. Гайдученко. Музей розмістився в орендованому будинку по вул. Малій
        Морській, 11 (ріг вул. Великої Морської). Городяни із захопленням розглядали першу експозицію, багато з них
        відгукнулись на пропозицію С.І. Гайдученка сприяти поповненню історичної колекції нового музею. В перші роки
        існування музейну колекцію поповнили численні подарунки – археологічні знахідки з Ольвії, етнографічні
        матеріали, побутові речі міських жителів, зразки холодної та вогнепальної зброї, документи, фотографії,
        моделі кораблів. У червні 1918 р. до фондосховищь надійшла колекція військового музею 58-го Празького
        піхотного полку.</p>
    <p>Незважаючи на бурхливі події революції та громадянської війни, музей не тільки зберіг свої експонати, а
        продовжував поповнюватися новими надходженнями. Згодом невелике приміщення вже не могло вмістити всю
        колекцію, тому на її базі було створено два музеї - історико-археологічний та природничий.</p>
    <p>Після смерті С.І. Гайдученка, з травня
        1923 по кінець вересня 1929 р., посаду директора займав археолог, краєзнавець Ф.Т. Камінський . У ті часи
        музей вже потребував нового приміщення. В результаті ним стала будівля колишньої гауптвахти на Соборному
        (Радянському) майдані. Після капітального ремонту 10 березня 1929 р. відбулося урочисте відкриття
        експозиції. На той час в зібранні музею було більше 19 тис. експонатів.</p>
    <p>28 квітня 1929 р. міська влада прийняла
        рішення про передачу музею будівлі Адміралтейського собору для виставки до 140-річчя Миколаєва, а потім під
        військово-морський відділ, в якому вже зберігалось 856 зразків зброї та військової атрибутики.</p>
    <p>На жаль, хвиля політичних репресій не обминула і музей, у вересні 1929 р. було заарештовано Ф.Т.
        Камінського, пізніше М.Д. Лагуту та інших представників творчої інтелігенції, які сприяли роботі
        закладу.</p>
    <p>У 30-ті рр. експозиція музею стала дуже
        заполітизованою, що знизило її науковий та естетичний рівень. В цей час музей природи знаходився в
        приміщенні колишнього реального училища (на розі вулиць Нікольської та Наваринської), його колекція
        налічувала 12 тис. експонатів. Восени 1936 р. в зв’язку з реконструкцією Радянського майдану зазнали
        руйнації Адміралтейський собор та гауптвахта, тому історико-археологічний музей перевезли до будівлі
        костьолу та двоповерхового будинку католицького священика (вул. Декабристів, 32).</p>
    <p>В період нацистської окупації та Другої світової війни музей продовжував працювати. При ньому діяла підпільна
        антифашистська організація під керівництвом Ю. Тарасова.</p>
    <p>На жаль, музейним співробітникам не вдалося повністю зберегти археологічні матеріали. В листопаді 1943 р.
        значну частину ольвійської колекції німці вивезли до Кенігсбергу, подальша доля цих експонатів невідома. У
        листопаді 1950 р. відбулося об’єднання історичного та природничого музеїв у Миколаївський обласний
        краєзнавчий музей, яким він залишається і зараз.</p>
    <p>У 1960-1980-ті рр. активізувалась науково-дослідницька та пошукова робота. Майже кожного року стали проводити
        комплексні експедиції в райони області та за їх межі. До фондів музею щорічно надходили нові артефакти.</p>
    <p>В цей період музей був змушений збирати матеріали партійних з’їздів, пленумів, «ударних» будівництв тощо. То
        була "обов’язкова програма", але продовжувалися археологічні дослідження степових курганів, поселень доби
        бронзи та античності. В ці часи розпочалось формування особистих фондів видатних миколаївців:
        інженера-технолога В.В. Рюміна, астрономів Б.П. Остащенко-Кудрявцева та Ф.О. Бредихіна, архіви просвітителя
        А.М. Топорова, поета М. Лисянського.</p>
    <p>Окрім цього, музеєм була придбана частина
        колекції російських пам’ятних медалей, зібраних родиною Ашиків. Одним з найцікавіших експонатів стала книга
        "Требник" П. Могили, надрукована в Києві в 1646 р.</p>
    <p>У 1970-1980-ті рр. музей зазнав суттєвих змін. Розширився штат співробітників, а до його структури увійшли
        новостворені філіали (територіально виділені відділи): у 1972 р. Очаківський військово-історичний музей ім.
        О.В. Суворова, у 1975 р. музей "Підпільно-партизанський рух на Миколаївщині в роки Великої Вітчизняної
        війни. 1941-1944 рр." (вул. Лягіна, 5). Великою подією для міста стало відкриття в липні 1978 р. Музею
        суднобудування та флоту – справжньої візитівки міста корабелів. В середині 80-х рр. ХХ ст. філіалами
        обласного краєзнавчого музею стали музей м. Первомайська та музей "Партизанська іскра" (с. Кримка).</p>
    <p>З 1985 по 1995 рр. музей (головна будівля по вул. Декабристів, 32) пережив не найкращі часи: довготривалий
        ремонт, неможливість відкриття повно-профільної експозиції, окрім цього музейне приміщення відійшло до
        католицького костьолу. Тривалий час працювали лише 2-3 виставкові зали.</p>
    <p>Проте велася постійна робота над поповненням музейної колекції. На початку 2000-х років музейне зібрання
        налічувало близько 180 тис. предметів. У 1999 р. Миколаївська облдержадміністрація прийняла рішення передати
        краєзнавчому музею будівлі комплексу "Старофлотські казарми" – пам’ятник архітектури національного значення,
        що був побудований у першій половині ХІХ ст. згідно проєкта англійського архітектора Ч.Акройда (вул.
        Набережна, 29). Ремонті роботи однієї з колишніх казарм були завершені до початку 2012 р. Через шість
        місяців в 18 залах була створена нова експозиція, яка відображає природно-екологічні особливості краю та
        історію північно-причорноморських земель від кам’яної доби до середньовіччя. Окрім постійної експозиції в
        музеї працюють три виставкові зали, в яких періодично демонструються художні та історичні виставки.</p>
    <p>Зараз у музеї функціонують п’ять відділів. Співробітники науково-експозиційного відділу займаються вивченням
        природних особливостей, екологічної ситуації нашого краю та його історії з найдавніших часів до сьогодення.
        Наші науковці проводять збір нових музейних предметів, здійснюють атрибуцію експонатів, беруть участь у
        науковому житті області та країни. Також в їх обов’язки входить створення виставок, обслуговування постійно
        діючої експозиції, розробка та проведення екскурсій і лекцій.</p>
{% endblock %}

djangoProject/templates/exhibition-delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <span>Видалити "{{ object }}"?</span>
        {{ form }}
        <input type="submit" value="Так">
    </form>
{% endblock %}

djangoProject/templates/exhibition-new.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Створити">
    </form>
{% endblock %}

djangoProject/templates/storage-delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Оновити">
    </form>
{% endblock %}

djangoProject/templates/storage-manage.html
{% extends 'base.html' %}
{% load in_group %}

{% block content %}
    {% if user.is_authenticated and user|in_group:"storage_manager" %}
        <h1>Предмет:</h1>
        <ul>
            <li>Назва: {{ item.name }}</li>
            <li>Кількість: {{ item.quantity }}</li>
        </ul>
        <a href="{% url 'storage-update' pk=item.id %}"><button>Змінити</button></a>
        <a href="{% url 'storage-delete' pk=item.id %}"><button>Видалити</button></a>
        <a href="{% url 'storage' %}"><button>До сховища</button></a>
    {% else %}
        <h1>Доступ відхилено.</h1>
    {% endif %}
{% endblock %}

djangoProject/templates/storage-new.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Створити">
    </form>
{% endblock %}

djangoProject/templates/storage-update.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Оновити">
    </form>
{% endblock %}

djangoProject/templates/ticket-delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <span>Видалити "{{ object }}"?</span>
        {{ form }}
        <input type="submit" value="Так">
    </form>
{% endblock %}

djangoProject/templates/ticket-new.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Створити">
    </form>
{% endblock %}

djangoProject/templates/tickets.html
{% extends 'base.html' %}
{% load in_group %}

{% block content %}
    {% if not user.is_authenticated %}
        <h1><a href="{% url 'login' %}">Увійдіть</a>, щоби переглянути цю сторінку.</h1>
    {% elif user|in_group:"ticketer" or user.is_staff %}
        <a href="{% url 'ticket-new' %}"><button>Створити</button></a>
        <h1>Усі квитки:</h1>
        <ul>
            {% for ticket in ticket_list %}
                <li> ({{ ticket.visitor.username }}) <span class="fw-bold"> {{ ticket.tour.date }} </span> - <span><a href="{% url 'ticket-manage' pk=ticket.tour.id %}">{{ ticket.tour.name }}</a></span></li>
            {% endfor %}
        </ul>
    {% else %}
        {% if ticket_list %}
            <h1>Ваші квитки:</h1>
            <ul>
            {% for ticket in ticket_list %}
                {% if ticket.visitor.id == user.id %}
                    <li><span class="fw-bold"> {{ ticket.tour.date }} </span> - <span> <a href="{% url 'tour-info' pk=ticket.tour.id %}">{{ ticket.tour.name }}</a> </span></li>
                {% endif %}
            {% endfor %}
            </ul>
        {% else %}
            <h1>У вас немає куплених квитків.</h1>
        {% endif %}
    {% endif %}
{% endblock %}

djangoProject/templates/tour-new.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Створити">
    </form>
{% endblock %}

djangoProject/templates/tour_detail.html
{% extends 'base.html' %}
{% load in_group %}

{% block content %}
    <h1>{{ tour.name }}</h1>

    <span>Дата екскурсії: {{ tour.date }}</span><br>
    {% if tour.exhibitions.all %}
    <span>Виставки:</span>
    <ul>
        {% for exhibition in tour.exhibitions.all %}
            <li>{{ exhibition.name }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <span>За записом? - {% if tour.admission %}Так{% else %}Ні{% endif %}</span><br>
    <span>Ціна: {% if tour.price == 0 %}Безкоштовно{% else %}{{ tour.price }} ₴{% endif %}</span>
{% endblock %}

djangoProject/templates/tour_update.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Оновити">
    </form>
{% endblock %}

djangoProject/templates/tours.html
{% extends 'base.html' %}
{% load in_group %}

{% block content %}
    {% if user.is_authenticated and user|in_group:"tours_manager" %}
    <a href="{% url 'tour-new' %}">
        <button>Створити</button>
    </a>
    <br>
    <h1>Екскурсії:</h1>
    {% if tour_list %}
        <ul>
            {% for tour in tour_list %}
            <li><a href="{{ tour.get_absolute_url }}">{{ tour.name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <span>Немає екскурсій.</span>
    {% endif %}
    {% else %}
        <h1>Доступ відхилено.</h1>
    {% endif %}
{% endblock %}